POST  http://localhost:4000/app/signupProfessional
Content-Type: application/json



 
{

"fullName": "Earlie",
  "email": "edantuoni2@zdnet.com",
  "phoneNo": "596-234-1920",
  "gender": "Female",
  "occupation": "Painter",
  "location": "Banglore",
  "password": "123",
  "experience": "Perfectionist.,Versatile.,Quick. 3 years"
}
 


