POST  http://localhost:8000/api/save
Content-Type: application/json



 
{

    "date":"1619284246893",
     "c_id":"60819fcdcad67e6c60745e10",
     "body":"hello",
     "location":"Hyderabad",
     "profession":"carpenter",
     "status":"Available",
}
 


